### ISSUE TITLE
Request Basketball Dataset

### ISSUE THREAD

**Issue by xiaoyandong08** [cgraber/cvpr_dNRI#1]
Hi, Colin. This is Yandong. I am really impressed with your work.
Is that possible to get the same Basketball Dataset from you? It's only for academic purposes.
I found this the original dataset from STATS is not available.

**Comment by cgraber** [comment]
Hi Yandong, thanks for your interest! I'll look into this - I want to make sure that sharing it won't get me into trouble first.

**Comment by cgraber** [comment]
Update: the data was once publicly available, but the owners removed it at some point in time. I'm not sure exactly why they decided to do this, but I'd rather not cause any problems by sharing data that I'm not authorized to share. It seems like I'm not the only one who has made this decision (see [this repo](https://github.com/ezhan94/multiagent-programmatic-supervision) for another example). Your best bet will be to contact them and see if they're willing to share it with you if you're using it for academic purposes.
