### ISSUE TITLE
Sparsity of interaction network inferred by dNRI

### ISSUE THREAD

**Issue by xiaoyandong08** [cgraber/cvpr_dNRI#2]
Dear author,

Thanks for your wonderful work. 

After executing the dNRI of 'run_motion_118.sh', I found the edges don't have zero element. How could I yield the sparsity (no interaction) of interaction networks?

Besides, what does '2 edge types' or '4 edge types' mean in CMU motion data?

**Comment by cgraber** [comment]
Hi, thanks for your interest!

To make sure I understand your first question: are you saying that you ran `run_motion_118.sh`, and the predicted edges are never the zero-th edge type? If so, how are you specifically extracting the edges?

dNRI infers a number of "relation types" (their meaning is not fixed ahead of time, and instead are learned from the data). The decoder contains a set of graph edge parameters for each relation type, and the set of parameters used at each time step for a given pair of variables corresponds to the edges type sampled from the encoder distribution for this pair at this time step.

To be clear, sparsity is achieved in the following way: there's a special flag that can be passed to the script -- `--skip_first` -- which fixes the zero-th edge as "no interaction." What this means is that, when this edge type is sampled by the network, no information is passed between these two variables (i.e. the "edge function" is skipped for this pair).
