### ISSUE TITLE
Traffic Trajectory Experiment

### ISSUE THREAD

**Issue by sancarlim** [cgraber/cvpr_dNRI#3]
Dear authors,

Thank you for such incredible work!
I would like to know if the traffic trajectory experiment will be published as well.

Thank you.

**Comment by EnnaSachdeva** [comment]
Great work.
I'd be interested in the traffic trajectory experiment. Could you please share the code corresponding to those experiments as well?

Thanks!

**Comment by cgraber** [comment]
Thanks for your interest! Apologies for the delay - dnri code for InD experiments has been added.

**Comment by EnnaSachdeva** [comment]
Thank you!
