### ISSUE TITLE
Basketball dataset preprocessing

### ISSUE THREAD

**Issue by mkofinas** [cgraber/cvpr_dNRI#6]
Hello Colin,

I downloaded the Basketball dataset from AWS exchange as documented here: https://github.com/ezhan94/multiagent-programmatic-supervision. However, the dataset seems to only contain a `train.npz` and a `test.npz` file, which are not the files that you use in your experiments. Is there an extra preprocessing step involved that I missed?

Thank you in advance.

**Comment by cgraber** [comment]
There is some extra preprocessing done on the data (the raw data contains the offense, defense, and basketball trajectories; it doesn't contain a val split). Now that the data is publicly available again, I've added a link to the preprocessed form of it used by this paper into the README.

**Comment by mkofinas** [comment]
Thank you for your answer and for sharing your preprocessed version of the dataset. I have a follow-up question regarding your evaluation protocol for this dataset. In the paper you mention that you train the model using 40 steps as input and evaluate using 30 steps. To my understanding, in order to get these results one has to change the following line in `dnri/experiments/bball_experiment.py` from

```python
test_cumulative_mse = evaluate.eval_forward_prediction(model, test_data, 40, 9, params)
```
to 
```python
test_cumulative_mse = evaluate.eval_forward_prediction(model, test_data, 30, 19, params)
```
Is my understanding correct? Are there any more changes required? I am asking because I tried evaluating your model with the aforementioned changes and the error curves are not the same as the ones mentioned in the paper.
Thank you for your time.

**Comment by cgraber** [comment]
Yes, your understanding is correct. It's odd that you're not getting the same error curves as shown in the paper. I'll see if I can figure out what's causing the issue.

**Comment by cgraber** [comment]
An update on this (apologies for the delay): I've been able to reproduce the error plots shown in the paper using my research codebase. I'll keep investigating.

**Comment by mkofinas** [comment]
Thank you for your response. In the meantime, I have also managed to reproduce the error plots shown in the paper, albeit with a slight variation in the standard deviation across different seeds. We can close the issue. Thanks again for your help!
