### ISSUE TITLE
reverse_rnn in dnri_dynamicvars.py

### ISSUE THREAD

**Issue by tiffanyyk** [cgraber/cvpr_dNRI#7]
Hi Colin,

Thanks for releasing the code of this wonderful work. I was going through dnri_dynamicvars.py and have trouble finding where the reverse LSTM in equation 14 of the paper is implemented. I noticed that DNRI_DynamicVars_Encoder.reverse_rnn is a recurrent layer, but it seems like it isn't used anywhere. Thanks in advance for your help!

**Comment by cgraber** [comment]
Hi Tiffany,

Thanks for pointing this out - when I was porting this code from the (larger, messier) original codebase, I somehow managed to omit the line where the reverse LSTM gets called. This has been fixed (and [is located here](https://github.com/cgraber/cvpr_dNRI/blob/master/dnri/models/dnri_dynamicvars.py#L512)).
